name: Lint
on: "pull_request"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      - run: "npm i"
      - run: "npx eslint --max-warnings=0 src/"
      - run: "npx prettier --check src/"
