name: Test
on: "pull_request"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}
      - run: "npm i"
      - run: "npm start &"
      - run: "tries=0; until nc -w 1 -vz 127.0.0.1 3000; do sleep 1; tries=$((tries+1)); if ((tries > 30)); then exit 1; fi; done"
      - run: "export PERCY_TOKEN=95baae51444701973348dbfbbd35621ff1b7da7bf54e2eacc2982b459a121354"
      - run: "npx cypress run"
